import { useMemo, useState } from 'react';
import { X, Loader2, Plus, ChevronDown } from 'lucide-react';
import { toast } from 'sonner';

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/lib/supabase';
import { TREATMENT_PRICES, formatRupiah, getTreatmentPrice } from '@/lib/treatment-prices';
import { PROMOS, getPromoById } from '@/lib/promos';
import { DOCTORS } from '@/context/role-context';

// The two real situations Robby described that put a patient on this list
// (plus "both at once"): wanting a specific doctor who has no slot free
// right now, and wanting a promo price that isn't running yet today/this
// week. Which one applies changes what the rest of the form requires —
// see needsDoctor/needsPromo below.
const REASONS = [
  { value: 'dokter', label: 'Menunggu Dokter Tersedia' },
  { value: 'promo', label: 'Menunggu Promo Tersedia' },
  { value: 'keduanya', label: 'Keduanya' },
];

const DOCTOR_OPTIONS_ANY = [...DOCTORS, 'Siapa saja'];

const initialForm = {
  name: '',
  phone: '',
  address: '',
  keluhan: '',
  treatment: '',
  reason: '',
  doctor: '',
  usePromo: false,
  promoId: '',
  waktuMode: 'ditentukan', // 'ditentukan' | 'fleksibel'
  date: '',
  time: '',
};

/**
 * "Add Waiting list" form — for a patient who can't be booked into a real
 * slot yet, for one of two reasons Robby explained: they want a specific
 * doctor who has no availability right now, or they want a promo price
 * that isn't running today/this week. "Keduanya" covers wanting both a
 * specific doctor AND a specific promo. No Figma design exists for this
 * one (only the sidebar's trigger button), so the layout follows the same
 * visual style as the "Buat Appointment" popup.
 *
 * Which reason is picked changes what's required below it: "Menunggu
 * Dokter Tersedia" (or "Keduanya") makes Pilih Dokter required and drops
 * the "Siapa saja" option — picking "someone, anyone" makes no sense when
 * the whole point is waiting for one particular doctor. "Menunggu Promo
 * Tersedia" (or "Keduanya") makes picking a promo required instead of the
 * optional checkbox+dropdown used when the reason is doctor-only.
 *
 * Distinct from the Dashboard's `waiting_list` table (SummaryCards.jsx) —
 * that one is a plain today-only name list for the dashboard's summary
 * card. This is a much richer, not-day-scoped intake record, so it gets
 * its own table.
 *
 * REQUIRES a one-time migration before this file works — run once in the
 * Supabase SQL Editor:
 *   create table if not exists appointment_waiting_list (
 *     id bigint generated by default as identity primary key,
 *     name text not null,
 *     phone text not null,
 *     address text,
 *     keluhan text,
 *     treatment text,
 *     reason text,
 *     doctor text,
 *     is_promo boolean not null default false,
 *     promo_label text,
 *     price bigint,
 *     is_flexible boolean not null default false,
 *     appt_date date,
 *     appt_time text,
 *     created_at timestamptz not null default now()
 *   );
 * (If this table already exists from an earlier version without `reason`,
 * just run: alter table appointment_waiting_list add column if not exists
 * reason text; — instead of the create table above.)
 * Without it, loading/adding/removing entries fails outright (same
 * "sandbox has no network" caveat as every other Supabase table in this
 * app applies here too when testing locally).
 */
export default function AddWaitingListDialog({ open, onOpenChange, onAdded }) {
  const [form, setForm] = useState(initialForm);
  const [saving, setSaving] = useState(false);

  const needsDoctor = form.reason === 'dokter' || form.reason === 'keduanya';
  const needsPromo = form.reason === 'promo' || form.reason === 'keduanya';
  // Whichever reason picked it, "there is a promo actively being tracked"
  // collapses to one flag — the optional checkbox only exists for the
  // doctor-only reason, where a promo is a nice-to-have, not the point.
  const promoActive = needsPromo || form.usePromo;

  const doctorOptions = needsDoctor ? DOCTORS : DOCTOR_OPTIONS_ANY;
  const normalPrice = useMemo(() => getTreatmentPrice(form.treatment), [form.treatment]);
  const selectedPromo = useMemo(() => getPromoById(form.promoId), [form.promoId]);
  const finalPrice = promoActive && selectedPromo ? selectedPromo.promoPrice : normalPrice;

  function update(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
  }

  // Switching reason can invalidate what's already picked (e.g. "Siapa
  // saja" stops being a valid doctor once the reason becomes
  // doctor-specific) — clearing both keeps the form from silently saving a
  // combination that doesn't match the reason it's filed under.
  function handleReasonChange(value) {
    setForm((prev) => ({ ...prev, reason: value, doctor: '', usePromo: false, promoId: '' }));
  }

  function resetAndClose() {
    setForm(initialForm);
    onOpenChange(false);
  }

  async function handleSubmit() {
    if (!form.name.trim()) {
      toast.error('Nama pasien wajib diisi');
      return;
    }
    if (!form.phone.trim()) {
      toast.error('Nomor telepon wajib diisi');
      return;
    }
    if (!form.reason) {
      toast.error('Pilih alasan waiting list terlebih dahulu');
      return;
    }
    if (needsDoctor && !form.doctor) {
      toast.error('Pilih dokter yang ditunggu');
      return;
    }
    if (needsPromo && !form.promoId) {
      toast.error('Pilih promo yang ditunggu');
      return;
    }
    if (form.waktuMode === 'ditentukan' && (!form.date || !form.time)) {
      toast.error('Isi tanggal & jam, atau pilih "Waktu Fleksibel"');
      return;
    }

    setSaving(true);
    const { data, error } = await supabase
      .from('appointment_waiting_list')
      .insert({
        name: form.name.trim(),
        phone: form.phone.trim(),
        address: form.address.trim() || null,
        keluhan: form.keluhan.trim() || null,
        treatment: form.treatment || null,
        reason: form.reason,
        doctor: form.doctor || null,
        is_promo: promoActive && !!selectedPromo,
        promo_label: promoActive ? selectedPromo?.label ?? null : null,
        price: finalPrice ?? null,
        is_flexible: form.waktuMode === 'fleksibel',
        appt_date: form.waktuMode === 'ditentukan' ? form.date : null,
        appt_time: form.waktuMode === 'ditentukan' ? form.time : null,
      })
      .select('id, name, phone, reason, doctor, is_promo, promo_label, price, is_flexible, appt_date, appt_time')
      .single();
    setSaving(false);

    if (error) {
      console.error('Failed to save waiting list entry', error);
      toast.error('Gagal menambahkan ke waiting list — coba lagi.');
      return;
    }

    toast.success(`${form.name.trim()} berhasil ditambahkan ke waiting list`);
    onAdded?.(data);
    resetAndClose();
  }

  return (
    <Dialog open={open} onOpenChange={(next) => (next ? onOpenChange(true) : resetAndClose())}>
      <DialogContent showCloseButton={false} className="overflow-hidden rounded-[20px] p-0 sm:max-w-[560px]">
        <DialogHeader className="relative gap-2 px-6 pt-6 pb-5">
          <DialogTitle className="text-[20px] font-semibold text-[#0f0d0a]">Add Waiting List</DialogTitle>
          <button
            type="button"
            aria-label="Close"
            onClick={resetAndClose}
            className="absolute right-6 top-6 flex size-7 items-center justify-center rounded-full bg-black/[0.03] text-[#0f0d0a] hover:bg-black/[0.06]"
          >
            <X className="size-3.5" />
          </button>
        </DialogHeader>
        <div className="h-px w-full shrink-0 bg-[#e2e8f0]" />

        <div className="flex max-h-[65vh] flex-col gap-4 overflow-y-auto px-6 py-5">
          <div className="flex w-full items-start gap-3">
            <div className="flex flex-1 flex-col gap-2">
              <p className="text-sm font-medium text-[#0f0d0a]">
                Nama <span className="text-[#dc2626]">*</span>
              </p>
              <input
                value={form.name}
                onChange={(e) => update('name', e.target.value)}
                placeholder="Nama pasien"
                className="w-full rounded-xl border border-[#e2e8f0] bg-white p-3 text-sm text-[#0f0d0a] placeholder:text-[#94a3b8] focus:outline-none focus:ring-2 focus:ring-green-600/20"
              />
            </div>
            <div className="flex flex-1 flex-col gap-2">
              <p className="text-sm font-medium text-[#0f0d0a]">
                No. Telp <span className="text-[#dc2626]">*</span>
              </p>
              <input
                value={form.phone}
                onChange={(e) => update('phone', e.target.value)}
                placeholder="08xx-xxxx-xxxx"
                className="w-full rounded-xl border border-[#e2e8f0] bg-white p-3 text-sm text-[#0f0d0a] placeholder:text-[#94a3b8] focus:outline-none focus:ring-2 focus:ring-green-600/20"
              />
            </div>
          </div>

          <div className="flex w-full flex-col gap-2 rounded-xl border border-[#e2e8f0] bg-[#f8fafc] p-3">
            <p className="text-sm font-medium text-[#0f0d0a]">
              Alasan Waiting List <span className="text-[#dc2626]">*</span>
            </p>
            <div className="flex flex-col gap-2">
              {REASONS.map((opt) => (
                <label key={opt.value} className="flex cursor-pointer items-center gap-2 text-sm text-[#404040]">
                  <input
                    type="radio"
                    name="waiting-reason"
                    className="size-4 accent-[#48a153]"
                    checked={form.reason === opt.value}
                    onChange={() => handleReasonChange(opt.value)}
                  />
                  {opt.label}
                </label>
              ))}
            </div>
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#0f0d0a]">Alamat</p>
            <textarea
              rows={2}
              value={form.address}
              onChange={(e) => update('address', e.target.value)}
              placeholder="Type here.."
              className="w-full resize-none rounded-xl border border-[#e2e8f0] bg-white p-3 text-sm text-[#0f0d0a] placeholder:text-[#94a3b8] focus:outline-none focus:ring-2 focus:ring-green-600/20"
            />
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#0f0d0a]">Keluhan</p>
            <textarea
              rows={2}
              value={form.keluhan}
              onChange={(e) => update('keluhan', e.target.value)}
              placeholder="Type here.."
              className="w-full resize-none rounded-xl border border-[#e2e8f0] bg-white p-3 text-sm text-[#0f0d0a] placeholder:text-[#94a3b8] focus:outline-none focus:ring-2 focus:ring-green-600/20"
            />
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#0f0d0a]">
              Pilih Dokter {needsDoctor && <span className="text-[#dc2626]">*</span>}
            </p>
            <div className="flex h-[42px] w-full items-center gap-4 rounded-xl border border-[rgba(15,13,10,0.08)] px-4">
              {doctorOptions.map((doctor) => (
                <label key={doctor} className="flex cursor-pointer items-center gap-2 text-sm text-[#404040]">
                  <input
                    type="radio"
                    name="waiting-doctor"
                    className="size-4 accent-[#48a153]"
                    checked={form.doctor === doctor}
                    onChange={() => update('doctor', doctor)}
                  />
                  {doctor}
                </label>
              ))}
            </div>
            {needsDoctor && (
              <p className="text-xs text-[#636363]">
                Dokter wajib dipilih spesifik — "Siapa saja" tidak berlaku kalau alasannya menunggu dokter ini.
              </p>
            )}
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#0f0d0a]">Pilih Tindakan</p>
            <div className="relative flex h-[42px] w-full items-center rounded-xl border border-[#e2e8f0] bg-white px-4">
              <select
                value={form.treatment}
                onChange={(e) => update('treatment', e.target.value)}
                className="w-full appearance-none bg-transparent text-sm text-[#0f0d0a] focus:outline-none"
              >
                <option value="">Pilih tindakan..</option>
                {TREATMENT_PRICES.map((t) => (
                  <option key={t.name} value={t.name}>
                    {t.name}
                  </option>
                ))}
              </select>
              <ChevronDown className="pointer-events-none absolute right-4 size-3.5 text-[#0f0d0a]" />
            </div>
          </div>

          <div className="flex w-full flex-col gap-2 rounded-xl border border-[#e2e8f0] bg-[#f8fafc] p-3">
            {needsPromo ? (
              <p className="text-sm font-medium text-[#0f0d0a]">
                Pilih Promo yang Ditunggu <span className="text-[#dc2626]">*</span>
              </p>
            ) : (
              <label className="flex cursor-pointer items-center gap-2 text-sm font-medium text-[#0f0d0a]">
                <input
                  type="checkbox"
                  className="size-4 accent-[#48a153]"
                  checked={form.usePromo}
                  onChange={(e) => {
                    const checked = e.target.checked;
                    setForm((prev) => ({ ...prev, usePromo: checked, promoId: checked ? prev.promoId : '' }));
                  }}
                />
                Pasien ini juga mau pakai harga promo (opsional)
              </label>
            )}
            {promoActive && (
              <div className="relative flex h-[42px] w-full items-center rounded-xl border border-[#e2e8f0] bg-white px-4">
                <select
                  value={form.promoId}
                  onChange={(e) => update('promoId', e.target.value)}
                  className="w-full appearance-none bg-transparent text-sm text-[#0f0d0a] focus:outline-none"
                >
                  <option value="">Pilih promo..</option>
                  {PROMOS.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.label} — {formatRupiah(p.promoPrice)}
                    </option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute right-4 size-3.5 text-[#0f0d0a]" />
              </div>
            )}
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#636363]">
              Harga <span className="font-normal">(Otomatis terisi)</span>
            </p>
            <div className="flex w-full items-center gap-2 rounded-xl border border-[#e2e8f0] bg-[#f5f3f2] p-3 text-sm">
              {promoActive && selectedPromo ? (
                <>
                  <span className="text-[#94a3b8] line-through">{formatRupiah(selectedPromo.normalPrice)}</span>
                  <span className="font-semibold text-[#16a34a]">{formatRupiah(selectedPromo.promoPrice)}</span>
                </>
              ) : (
                <span className="text-[#0f0d0a]">{formatRupiah(normalPrice)}</span>
              )}
            </div>
          </div>

          <div className="flex w-full flex-col gap-2">
            <p className="text-sm font-medium text-[#0f0d0a]">Waktu</p>
            <div className="flex items-center gap-6">
              {[
                { value: 'ditentukan', label: 'Ditentukan' },
                { value: 'fleksibel', label: 'Fleksibel / Sewaktu-waktu' },
              ].map((opt) => (
                <label key={opt.value} className="flex cursor-pointer items-center gap-2 text-sm text-[#404040]">
                  <input
                    type="radio"
                    name="waktu-mode"
                    className="size-4 accent-[#48a153]"
                    checked={form.waktuMode === opt.value}
                    onChange={() => update('waktuMode', opt.value)}
                  />
                  {opt.label}
                </label>
              ))}
            </div>
            {form.waktuMode === 'ditentukan' ? (
              <div className="flex w-full items-center gap-3">
                <input
                  type="date"
                  value={form.date}
                  onChange={(e) => update('date', e.target.value)}
                  className="h-[42px] flex-1 rounded-xl border border-[#e2e8f0] bg-white px-4 text-sm text-[#0f0d0a] focus:outline-none focus:ring-2 focus:ring-green-600/20"
                />
                <input
                  type="time"
                  value={form.time}
                  onChange={(e) => update('time', e.target.value)}
                  className="h-[42px] flex-1 rounded-xl border border-[#e2e8f0] bg-white px-4 text-sm text-[#0f0d0a] focus:outline-none focus:ring-2 focus:ring-green-600/20"
                />
              </div>
            ) : (
              <p className="rounded-xl border border-dashed border-[#e2e8f0] bg-[#f8fafc] p-3 text-sm text-[#636363]">
                Belum ada jadwal pasti — pasien akan dihubungi begitu ada slot yang cocok.
              </p>
            )}
          </div>
        </div>

        <div className="h-px w-full shrink-0 bg-[#e2e8f0]" />
        <div className="flex items-center justify-between bg-[#faf9f9] px-5 py-5">
          <button
            type="button"
            onClick={resetAndClose}
            className="rounded-xl border border-solid border-[#dc2626] bg-white px-6 py-3 text-sm font-semibold text-[#dc2626] hover:bg-red-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSubmit}
            disabled={saving}
            className="inline-flex items-center gap-2 rounded-xl bg-[#48a153] px-6 py-3 text-sm font-semibold text-white hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-70"
          >
            {saving ? <Loader2 className="size-3.5 animate-spin" /> : <Plus className="size-3.5" />}
            Tambah ke Waiting List
          </button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
