import { useEffect, useMemo, useState } from 'react';
import { NotebookPen, UsersRound, Users, Stethoscope, Plus, X } from 'lucide-react';
import { toast } from 'sonner';

import { cn } from '@/lib/utils';
import { supabase } from '@/lib/supabase';
import { StatCard, DetailHighlightToggle } from '@/components/stat-card';
import { isWaitingStatus } from '@/lib/wait-estimate';
// The clinic's fixed roster of doctors — same source Registration.jsx's
// appointment-doctor picker and the login screen's account list use, so
// "Doctor Available" can never list a doctor that doesn't actually exist
// in the system (or miss one that does).
import { DOCTORS } from '@/context/role-context';

// Both Sticky notes and Waiting list are plain manual lists (not derived
// from `patients`/the appointments table) that reset themselves every day —
// each row is stamped with the date it was written on, so opening the page
// on a new day naturally starts from an empty list instead of yesterday's
// leftovers, without anyone having to remember to clear it. Persisted to
// Supabase (rather than this browser's own storage) so the same list shows
// up for every receptionist/admin, on any device, for as long as it's still
// today.
//
// REQUIRES a one-time migration before this file works — run once in the
// Supabase SQL Editor:
//   create table if not exists sticky_notes (
//     id bigint generated by default as identity primary key,
//     note_date date not null,
//     text text not null,
//     created_at timestamptz not null default now()
//   );
//   create index if not exists sticky_notes_note_date_idx on sticky_notes (note_date);
//
//   create table if not exists waiting_list (
//     id bigint generated by default as identity primary key,
//     note_date date not null,
//     patient_name text not null,
//     created_at timestamptz not null default now()
//   );
//   create index if not exists waiting_list_note_date_idx on waiting_list (note_date);
// Without it, loading or adding to either list fails outright.
function getTodayDateStr() {
  return new Date().toISOString().slice(0, 10);
}

// The four Status Patient buckets, matched against a real patient list
// (Today's Patient's status field) — used for both the doctor-scoped
// variant (that doctor's own roster) and the Receptionist/Admin variant
// (the full today's roster). This used to be a fixed mock (STATUS_BREAKDOWN,
// 19/1/2/2) shown only for Receptionist/Admin — a leftover from before the
// Supabase migration that never got wired up, so it silently never matched
// what the table below it actually showed.
//
// isWaitingStatus lives in lib/wait-estimate.js (shared with TodaysPatient's
// live wait-time estimate) so "Dalam Antrean" counting as part of the
// "Waiting" family can't drift between the two places that need to agree on it.

const STATUS_BUCKETS = [
  { label: 'Waiting', dot: 'bg-orange-500', match: isWaitingStatus },
  { label: 'Complete', dot: 'bg-green-500', match: (s) => s === 'Complete' },
  { label: 'Late', dot: 'bg-purple-500', match: (s) => s === 'Late' },
  { label: 'Cancel', dot: 'bg-red-500', match: (s) => s === 'Cancel' },
];

// The clinic's operating window used to work out each doctor's *free*
// gaps today (08:00-17:00) — appointments in this app have never been
// seen outside that range, and there's no "clinic hours" setting anywhere
// else in the app to read this from instead.
const CLINIC_OPEN_MIN = 8 * 60;
const CLINIC_CLOSE_MIN = 17 * 60;

// appt_time is stored as a plain "HH:MM" string — converts it to minutes
// since midnight so busy/free ranges can be compared and merged as plain
// numbers instead of juggling string comparisons.
function parseTimeToMinutes(hhmm) {
  if (!hhmm || typeof hhmm !== 'string' || !hhmm.includes(':')) return null;
  const [h, m] = hhmm.split(':').map(Number);
  if (Number.isNaN(h) || Number.isNaN(m)) return null;
  return h * 60 + m;
}

// durasi is a free-form label like "30 Min" (or "-" for the register-only
// fast-track in Registration.jsx, which never got a real appointment
// length). Pulls out the leading number, falling back to a conservative
// 30-minute default when there isn't one, so a missing/placeholder
// duration still blocks *some* time instead of collapsing to a zero-
// length (and therefore invisible) busy slot.
function parseDurationMinutes(durasi) {
  const match = typeof durasi === 'string' ? durasi.match(/\d+/) : null;
  return match ? Number(match[0]) : 30;
}

function formatMinutes(mins) {
  const h = String(Math.floor(mins / 60)).padStart(2, '0');
  const m = String(mins % 60).padStart(2, '0');
  return `${h}:${m}`;
}

/**
 * Top-of-dashboard summary section: four stat cards (Sticky notes,
 * Waiting list, Status Patient, Doctor Available) plus a "Show/Hide Detail
 * Highlight" toggle that expands each card in place to reveal its
 * breakdown. The first three match Figma nodes 583:4311 (Show/collapsed)
 * and 583:4583 (Hide/expanded), redrawn with a flatter, more minimal
 * visual style; Doctor Available adds the same row's node 719:2071.
 *
 * Each card is a real accordion (height animates from its collapsed row
 * to its measured content height and back), so both expanding *and*
 * collapsing animate smoothly — no swapping between differently-shaped
 * DOM trees, which is what made the previous crossfade-based version
 * look abrupt on hide.
 *
 * Sticky notes and Waiting list are both plain manual lists — add/edit/
 * delete free text (Sticky notes) or just a patient's name (Waiting list)
 * — persisted to Supabase's `sticky_notes`/`waiting_list` tables scoped to
 * today's date (see the migration comment above), not derived from
 * `patients` at all. That also means neither one is "static": they survive
 * a page reload (same day, same list) but start empty again once the date
 * rolls over, since a new day has no rows stamped with that `note_date` yet.
 *
 * `patients` is Today's Patient's real roster (Supabase-backed, not mock) —
 * for a Doctor it's already filtered to just their own patients, for
 * Receptionist/Admin it's everyone today. Status Patient and Doctor
 * Available are computed live from it; Sticky notes and Waiting list are
 * not (see above) — they used to double as a mock/manual stand-in for real
 * per-doctor wait data, but that read as more automatic than it actually
 * was, so it's now an explicitly manual list instead.
 */
export default function SummaryCards({ patients }) {
  const [showDetail, setShowDetail] = useState(false);
  const [notes, setNotes] = useState([]);
  const [newNote, setNewNote] = useState('');
  const [waitingNames, setWaitingNames] = useState([]);
  const [newWaitingName, setNewWaitingName] = useState('');

  // Load today's Sticky notes + Waiting list once on mount. Both are scoped
  // to `getTodayDateStr()` at the moment the page opens — leaving the page
  // open across midnight won't roll the list over on its own, but a reload
  // after midnight will (see the migration comment above the tables).
  useEffect(() => {
    const todayStr = getTodayDateStr();

    supabase
      .from('sticky_notes')
      .select('id, text')
      .eq('note_date', todayStr)
      .order('created_at', { ascending: true })
      .then(({ data, error }) => {
        if (error) {
          console.error('Failed to load sticky notes', error);
          toast.error('Gagal memuat sticky notes.');
          return;
        }
        setNotes(data ?? []);
      });

    supabase
      .from('waiting_list')
      .select('id, patient_name')
      .eq('note_date', todayStr)
      .order('created_at', { ascending: true })
      .then(({ data, error }) => {
        if (error) {
          console.error('Failed to load waiting list', error);
          toast.error('Gagal memuat waiting list.');
          return;
        }
        setWaitingNames((data ?? []).map((row) => ({ id: row.id, name: row.patient_name })));
      });
  }, []);

  async function addNote() {
    const trimmed = newNote.trim();
    if (!trimmed) return;
    setNewNote('');

    const { data, error } = await supabase
      .from('sticky_notes')
      .insert({ note_date: getTodayDateStr(), text: trimmed })
      .select('id, text')
      .single();

    if (error) {
      console.error('Failed to save sticky note', error);
      toast.error('Catatan gagal disimpan — coba lagi.');
      setNewNote(trimmed);
      return;
    }
    setNotes((prev) => [...prev, data]);
  }

  function updateNote(id, value) {
    setNotes((prev) => prev.map((note) => (note.id === id ? { ...note, text: value } : note)));
  }

  async function persistNote(id) {
    const note = notes.find((n) => n.id === id);
    if (!note) return;
    const { error } = await supabase.from('sticky_notes').update({ text: note.text }).eq('id', id);
    if (error) {
      console.error('Failed to update sticky note', error);
      toast.error('Perubahan catatan gagal disimpan.');
    }
  }

  async function removeNote(id) {
    const removed = notes.find((n) => n.id === id);
    setNotes((prev) => prev.filter((n) => n.id !== id));

    const { error } = await supabase.from('sticky_notes').delete().eq('id', id);
    if (error) {
      console.error('Failed to delete sticky note', error);
      toast.error('Catatan gagal dihapus — coba lagi.');
      if (removed) setNotes((prev) => [...prev, removed]);
    }
  }

  async function addWaitingName() {
    const trimmed = newWaitingName.trim();
    if (!trimmed) return;
    setNewWaitingName('');

    const { data, error } = await supabase
      .from('waiting_list')
      .insert({ note_date: getTodayDateStr(), patient_name: trimmed })
      .select('id, patient_name')
      .single();

    if (error) {
      console.error('Failed to save waiting list entry', error);
      toast.error('Nama pasien gagal disimpan — coba lagi.');
      setNewWaitingName(trimmed);
      return;
    }
    setWaitingNames((prev) => [...prev, { id: data.id, name: data.patient_name }]);
  }

  async function removeWaitingName(id) {
    const removed = waitingNames.find((n) => n.id === id);
    setWaitingNames((prev) => prev.filter((n) => n.id !== id));

    const { error } = await supabase.from('waiting_list').delete().eq('id', id);
    if (error) {
      console.error('Failed to delete waiting list entry', error);
      toast.error('Nama pasien gagal dihapus — coba lagi.');
      if (removed) setWaitingNames((prev) => [...prev, removed]);
    }
  }

  const roster = patients ?? [];

  const statusBreakdown = useMemo(
    () =>
      STATUS_BUCKETS.map((bucket) => ({
        label: bucket.label,
        dot: bucket.dot,
        value: roster.filter((p) => bucket.match(p.status)).length,
      })),
    [roster]
  );

  // One schedule per clinic doctor (not just the doctors who happen to
  // appear in `roster` today — a doctor with zero bookings still needs to
  // show up as fully available), built straight from `roster`'s own
  // `dokter`/`appt`/`durasi`/`status` fields. This is the live connection
  // to the Today's Patient table the card is meant to reflect: a new
  // booking, a cancellation, or a duration change on that table changes
  // what this card shows on the very next render, with no separate data
  // source of its own.
  const doctorSchedules = useMemo(() => {
    const nowMin = (() => {
      const now = new Date();
      return now.getHours() * 60 + now.getMinutes();
    })();

    return DOCTORS.map((doctor) => {
      // A cancelled slot never actually happens — same "what counts as a
      // real visit" rule lib/patients.js's summarizeVisits uses for a
      // patient's history — so it doesn't block the doctor's time here
      // either. Every other status (including a past "Complete" one)
      // still reflects a real slot on today's schedule.
      const rawBusy = roster
        .filter((p) => p.dokter === doctor && p.status !== 'Cancel')
        .map((p) => {
          const start = parseTimeToMinutes(p.appt);
          if (start == null) return null;
          const end = start + parseDurationMinutes(p.durasi);
          return { start, end };
        })
        .filter(Boolean)
        .sort((a, b) => a.start - b.start);

      // Merge overlapping/back-to-back bookings into one continuous block
      // — otherwise two appointments booked back-to-back would render as
      // separate chips with an artificial (and wrong) 0-minute "free" gap
      // between them.
      const busy = [];
      for (const slot of rawBusy) {
        const last = busy[busy.length - 1];
        if (last && slot.start <= last.end) {
          last.end = Math.max(last.end, slot.end);
        } else {
          busy.push({ ...slot });
        }
      }

      // Free = the complement of `busy` inside today's clinic hours.
      const free = [];
      let cursor = CLINIC_OPEN_MIN;
      for (const slot of busy) {
        const start = Math.max(slot.start, CLINIC_OPEN_MIN);
        if (start > cursor) free.push({ start: cursor, end: Math.min(start, CLINIC_CLOSE_MIN) });
        cursor = Math.max(cursor, Math.min(slot.end, CLINIC_CLOSE_MIN));
      }
      if (cursor < CLINIC_CLOSE_MIN) free.push({ start: cursor, end: CLINIC_CLOSE_MIN });

      const isAvailableNow = !busy.some((slot) => nowMin >= slot.start && nowMin < slot.end);

      return { doctor, busy, free, isAvailableNow };
    });
  }, [roster]);

  // Collapsed-state count: how many of the clinic's doctors are free at
  // this exact moment — the number a receptionist glancing at the row of
  // cards actually wants ("can I book someone in right now"), same idea
  // as "Waiting list"'s count being how many patients are waiting right
  // now rather than some other total.
  const doctorsAvailableNow = doctorSchedules.filter((d) => d.isAvailableNow).length;

  return (
    <div className="flex w-full flex-col gap-3">
      <DetailHighlightToggle expanded={showDetail} onToggle={() => setShowDetail((v) => !v)} />

      <div className="flex w-full flex-wrap items-start gap-4">
        {/* Sticky notes — free-text notes: type to add, click a note to
            edit in place (persisted on blur), hover to reveal a delete
            button. Backed by Supabase's `sticky_notes` table, scoped to
            today's date — not a hardcoded default list, and not lost on
            reload; see the migration comment near the top of this file. */}
        <StatCard
          icon={<NotebookPen className="size-4" />}
          title="Sticky notes"
          count={notes.length}
          showDetail={showDetail}
        >
          <div className="flex flex-col gap-0.5 overflow-y-auto">
            {notes.map((note) => (
              <div
                key={note.id}
                className="group flex items-center gap-2 rounded-md px-1.5 py-1 hover:bg-slate-50"
              >
                <span className="size-1 shrink-0 rounded-full bg-slate-300" />
                <input
                  value={note.text}
                  onChange={(e) => updateNote(note.id, e.target.value)}
                  onBlur={() => persistNote(note.id)}
                  className="w-full min-w-0 rounded border border-transparent bg-transparent text-[13px] text-slate-700 outline-none focus:border-slate-200 focus:bg-white"
                />
                <button
                  type="button"
                  aria-label={`Hapus catatan ${note.text}`}
                  onClick={() => removeNote(note.id)}
                  className="shrink-0 text-slate-300 opacity-0 hover:text-slate-500 group-hover:opacity-100"
                >
                  <X className="size-3.5" />
                </button>
              </div>
            ))}
            <div className="flex items-center gap-2 rounded-md px-1.5 py-1">
              <Plus className="size-3 shrink-0 text-slate-400" />
              <input
                value={newNote}
                onChange={(e) => setNewNote(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    addNote();
                  }
                }}
                onBlur={addNote}
                placeholder="Tambah catatan..."
                className="w-full min-w-0 rounded border border-transparent bg-transparent text-[13px] text-slate-700 outline-none placeholder:text-slate-400 focus:border-slate-200 focus:bg-white"
              />
            </div>
          </div>
        </StatCard>

        {/* Waiting list — a manual list of patient names only (not derived
            from Today's Patient's appointment statuses anymore): type a
            name to add, hover to reveal a delete button. Backed by
            Supabase's `waiting_list` table, scoped to today's date, same as
            Sticky notes above. */}
        <StatCard
          icon={<UsersRound className="size-4" />}
          title="Waiting list"
          count={waitingNames.length}
          showDetail={showDetail}
        >
          <div className="flex flex-col gap-0.5 overflow-y-auto">
            {waitingNames.map((entry) => (
              <div
                key={entry.id}
                className="group flex items-center gap-2 rounded-md px-1.5 py-1 hover:bg-slate-50"
              >
                <span className="size-1 shrink-0 rounded-full bg-slate-300" />
                <span className="w-full min-w-0 text-[13px] text-slate-700">{entry.name}</span>
                <button
                  type="button"
                  aria-label={`Hapus ${entry.name} dari waiting list`}
                  onClick={() => removeWaitingName(entry.id)}
                  className="shrink-0 text-slate-300 opacity-0 hover:text-slate-500 group-hover:opacity-100"
                >
                  <X className="size-3.5" />
                </button>
              </div>
            ))}
            <div className="flex items-center gap-2 rounded-md px-1.5 py-1">
              <Plus className="size-3 shrink-0 text-slate-400" />
              <input
                value={newWaitingName}
                onChange={(e) => setNewWaitingName(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    addWaitingName();
                  }
                }}
                onBlur={addWaitingName}
                placeholder="Tambah nama pasien..."
                className="w-full min-w-0 rounded border border-transparent bg-transparent text-[13px] text-slate-700 outline-none placeholder:text-slate-400 focus:border-slate-200 focus:bg-white"
              />
            </div>
          </div>
        </StatCard>

        {/* Status patient breakdown — real counts from today's roster
            (this doctor's own patients when doctor-scoped, everyone
            today for Receptionist/Admin). */}
        <StatCard
          icon={<Users className="size-4" />}
          title="Status Patient"
          count={roster.length}
          showDetail={showDetail}
        >
          <div className="grid flex-1 grid-cols-4 gap-2">
            {statusBreakdown.map((item) => (
              <div
                key={item.label}
                className="flex flex-col items-center justify-center gap-1.5 rounded-lg bg-slate-50/60 py-2"
              >
                <p className="text-xl font-semibold text-slate-800">{item.value}</p>
                <div className="flex items-center gap-1">
                  <span className={cn('size-1.5 rounded-full', item.dot)} />
                  <span className="text-[11px] font-medium text-slate-500">{item.label}</span>
                </div>
              </div>
            ))}
          </div>
        </StatCard>

        {/* Doctor Available — per Figma node 719:2071. Count is how many
            of the clinic's doctors are free right now; expanding the row
            breaks that down per doctor into the actual hours they're
            already booked ("Appointment") vs. still open ("Available"),
            both derived live from `roster` (Today's Patient's real
            table), not a separate schedule of their own. */}
        <StatCard
          icon={<Stethoscope className="size-4" />}
          title="Doctor Available"
          count={doctorsAvailableNow}
          showDetail={showDetail}
        >
          <div className="flex flex-col gap-1.5 overflow-y-auto">
            {doctorSchedules.map((d) => (
              <div
                key={d.doctor}
                className="rounded-lg border border-slate-100 bg-slate-50/60 px-3 py-1.5"
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-xs font-medium text-slate-700">{d.doctor}</span>
                  <span
                    className={cn(
                      'flex shrink-0 items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold',
                      d.isAvailableNow ? 'bg-green-50 text-green-600' : 'bg-orange-50 text-orange-600'
                    )}
                  >
                    <span className={cn('size-1.5 rounded-full', d.isAvailableNow ? 'bg-green-500' : 'bg-orange-500')} />
                    {d.isAvailableNow ? 'Available now' : 'In appointment'}
                  </span>
                </div>
                <div className="mt-1 flex flex-wrap items-center gap-1">
                  <span className="text-[10px] font-semibold text-slate-400">Appt</span>
                  {d.busy.length === 0 ? (
                    <span className="text-[11px] text-slate-400">—</span>
                  ) : (
                    d.busy.map((slot, i) => (
                      <span
                        key={i}
                        className="rounded-full bg-white px-1.5 py-0.5 text-[11px] font-medium text-slate-600 ring-1 ring-slate-200"
                      >
                        {formatMinutes(slot.start)}–{formatMinutes(slot.end)}
                      </span>
                    ))
                  )}
                </div>
                <div className="mt-1 flex flex-wrap items-center gap-1">
                  <span className="text-[10px] font-semibold text-slate-400">Bebas</span>
                  {d.free.length === 0 ? (
                    <span className="text-[11px] text-slate-400">—</span>
                  ) : (
                    d.free.map((slot, i) => (
                      <span
                        key={i}
                        className="rounded-full bg-green-50 px-1.5 py-0.5 text-[11px] font-medium text-green-700 ring-1 ring-green-100"
                      >
                        {formatMinutes(slot.start)}–{formatMinutes(slot.end)}
                      </span>
                    ))
                  )}
                </div>
              </div>
            ))}
          </div>
        </StatCard>
      </div>
    </div>
  );
}
